M48
; DRILL file {KiCad 7.0.7} date 2024 April 28, Sunday 08:46:15
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-28T08:46:15+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X6.1213Y-4.0902
T2
X4.15Y-5.25
X6.45Y-4.0
T0
M30
